### ISSUE TITLE
Intended Behavior: Teachers as Students?

### ISSUE THREAD

**Issue by neloe** [raybox94/GDPproject03#7]
When I add a class with a roster that contains myself as a student, the class does not appear in my student dashboard.  Is this the intended behavior?  I believe we discussed that instructors should be considered as students as well...

**Comment by AnkitPrakash687** [comment]
Fix

**Comment by AnkitPrakash687** [comment]
Teacher can act as a student in his course. Fix the issue.

**Comment by AnkitPrakash687** [comment]
You need to finalize the course before it appears in the dashboard.
